name: ECJ Non-regression Builds

on:
  workflow_dispatch:
    inputs:
      ecj_sha:
        description: "ECJ commit SHA to test"
        required: false

jobs:
  build-ecj:
    runs-on: ubuntu-latest
    outputs:
      ecj_sha: ${{ steps.get-sha.outputs.sha }}
    steps:
      - name: Checkout ECJ repo
        run: |
          git clone https://github.com/eclipse-jdt/eclipse.jdt.core.git ecj
          cd ecj
          if [ -n "${{ github.event.inputs.ecj_sha }}" ]; then
            git checkout ${{ github.event.inputs.ecj_sha }}
          fi

      - id: get-sha
        run: |
          cd ecj
          SHA=$(git rev-parse HEAD)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Build ECJ with Maven
        run: |
          cd ecj
          mvn -B -DskipTests clean install \
            -pl org.eclipse.jdt.core.compiler.batch -am \
            > ../ecj-build.log 2>&1
            
      - name: Rename ECJ jar
        run: |
          cd ecj/org.eclipse.jdt.core.compiler.batch/target
          JAR=$(ls org.eclipse.jdt.core.compiler.batch-*.jar | grep -v 'sources')
          cp "$JAR" ecj-SNAPSHOT.jar
       
      - name: Upload ECJ build log
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ecj-build.log
          path: ecj-build.log

      - name: Upload ECJ jar
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ecj-SNAPSHOT.jar
          path: ecj/org.eclipse.jdt.core.compiler.batch/target/ecj-SNAPSHOT.jar

  setup-matrix:
    runs-on: ubuntu-latest
    needs: build-ecj
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      ecj_sha: ${{ needs.build-ecj.outputs.ecj_sha }}
    steps:
      - name: Checkout ECJ test harness
        uses: actions/checkout@v5

      - id: set-matrix
        run: |
            PROJECTS=$(jq -c . < projects.json)
            echo "matrix={\"include\":$PROJECTS}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup-matrix.outputs.matrix) }}
    steps:
      - name: Checkout ECJ test harness
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Download ECJ jar
        uses: actions/download-artifact@v5
        with:
          name: ecj-SNAPSHOT.jar
          path: libs

      - name: Install ECJ jar to local Maven repo
        run: |
          mvn install:install-file \
              -Dfile="libs/ecj-SNAPSHOT.jar" \
              -DgroupId=org.eclipse.jdt \
              -DartifactId=ecj \
              -Dversion=SNAPSHOT \
              -Dpackaging=jar

      - name: Run ECJ compilation
        run: bash scripts/run-build.sh "${{ matrix.name }}" "${{ matrix.url }}" "${{ matrix.cmd }}"

      - name: Upload partial result
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ matrix.name }}.md
          path: "results/${{ matrix.name }}.md"
          if-no-files-found: ignore

      - name: Upload logs
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ matrix.name }}.log
          path: "logs/${{ matrix.name }}.log"
          if-no-files-found: ignore
