name: ECJ Non-regression Tests

on:
  workflow_dispatch:
    inputs:
      ecj_sha:
        description: "ECJ commit SHA to test"
        required: false
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours

jobs:
  build-ecj:
    runs-on: ubuntu-latest
    outputs:
      ecj_sha: ${{ steps.get-sha.outputs.sha }}
    steps:
      - name: Checkout ECJ repo
        run: |
          git clone https://github.com/eclipse-jdt/eclipse.jdt.core.git ecj
          cd ecj
          if [ -n "${{ github.event.inputs.ecj_sha }}" ]; then
            git checkout ${{ github.event.inputs.ecj_sha }}
          fi

      - id: get-sha
        run: |
          cd ecj
          SHA=$(git rev-parse HEAD)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build ECJ with Maven
        run: |
          cd ecj
          mvn -B -DskipTests clean install \
            -pl org.eclipse.jdt.core.compiler.batch -am \
            > ../ecj-build.log 2>&1

      - name: Upload ECJ build log
        uses: actions/upload-artifact@v4
        with:
          name: ecj-build-log
          path: ecj-build.log

      - name: Upload ECJ jar
        uses: actions/upload-artifact@v4
        with:
          name: ecj-jar
          path: ecj/org.eclipse.jdt.core.compiler.batch/target/org.eclipse.jdt.core.compiler.batch-*.jar

  setup-matrix:
    runs-on: ubuntu-latest
    needs: build-ecj
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      ecj_sha: ${{ needs.build-ecj.outputs.ecj_sha }}
    steps:
      - name: Checkout ECJ test harness
        uses: actions/checkout@v4

      - id: set-matrix
        run: |
          PROJECTS=$(jq -R . < projects.txt | jq -s .)
          echo "matrix={\"project\":$PROJECTS}" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup-matrix.outputs.matrix) }}
    steps:
      - name: Checkout ECJ test harness
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Download ECJ jar
        uses: actions/download-artifact@v4
        with:
          name: ecj-jar
          path: ecj-jar

      - name: Run ECJ compilation
        run: bash scripts/run-tests.sh "${{ matrix.project }}"

      - name: Upload partial result
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: result-*.md
          if-no-files-found: ignore

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: "*.log"
          if-no-files-found: ignore

  aggregate:
    runs-on: ubuntu-latest
    needs: [test, setup-matrix]
    steps:
      - name: Download results
        uses: actions/download-artifact@v4
        with:
          name: results
          path: results

      - name: Download logs
        uses: actions/download-artifact@v4
        with:
          name: logs
          path: logs

      - name: Download ECJ build log
        uses: actions/download-artifact@v4
        with:
          name: ecj-build-log
          path: .

      - name: Build summary
        run: |
          SHA="${{ needs.setup-matrix.outputs.ecj_sha || 'N/A (scheduled run)' }}"

          echo "# ECJ Compatibility Report" > report.md
          echo "" >> report.md
          echo "**Tested ECJ commit:** $SHA" >> report.md
          echo "" >> report.md
          echo "| Project | Status |" >> report.md
          echo "|---------|--------|" >> report.md
          cat results/result-*.md >> report.md

          echo "## ECJ Compatibility Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Tested ECJ commit:** $SHA" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Project | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|---------|--------|" >> $GITHUB_STEP_SUMMARY
          cat results/result-*.md >> $GITHUB_STEP_SUMMARY

      - name: Upload final report
        uses: actions/up
